main: fr.Maxime3399.MCube.MainClass
author: Maxime3399
name: M-Cube
version: 1.0.0-a1.0
api-version: 1.13
commands:
    menu:
    maintenance:
    playercount:
    pc:
    gift:
    ccmd:
    stop:
    playertime:
    pt:
    lastconnection:
    lc:
    chest:
    home:
    sethome:
    delhome:
    fly: